# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  build:
    docker:
      - image: cimg/node:16.10.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
  tests:
    docker:
      - image: cimg/node:16.10.0
    steps:
      - checkout
      - run:
          name: Run tests
          command: npm run test
workflows:
  commit-workflow:
    jobs:
      - build
      - tests:
          requires:
            - build