# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  run_tests:
    docker:
      - image: cimg/node:16.10.0
    steps:
      - checkout
      - run:
        name: Install dependencies
        command: 
          npm install --save
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
workflow:
  build_test:
    jobs:
      - run_tests

