version: 2.1
orbs:
  node: circleci/node@4.7
jobs:
  build-and-test:
    docker:
      - image: cimg/node:16.10
      - image: cimg/node:16.10.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test
workflows:
  sample:
    jobs:
      - build-and-test